modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="pritchvolution"
version="1.0.0"
displayName="pritchvolution"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.pritchvolution]]
modId="neoforge"
type="required"
versionRange="[21.1.176,)"
ordering="AFTER"
side="BOTH"

[[dependencies.pritchvolution]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"





# Start of user code block custom mixins
# End of user code block custom mixins


# Start of user code block dependencies configuration
# End of user code block dependencies configuration